name: 'Run main workflow'

on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run check
        run: ./mvnw -B clean verify

  release-snapshot:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    needs:
      - build
    if: ${{ github.ref_type != 'tag' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish snapshot to maven central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
        run: ./mvnw -B deploy -DskipTests -Pdeploy

  release:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    needs:
      - build
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Configure git
        run: |
          git config user.name "gigasproule-actions-bot[bot]"
          git config user.email "201257440+gigasproule-actions-bot[bot]@users.noreply.github.com"
      - name: Set version for release
        run: |
          ./mvnw versions:set -DnewVersion="${{ github.ref_name }}"
      - name: Commit release version
        run: |
          git add pom.xml
          git commit -m "chore: set version to ${{ github.ref_name }}"
      - name: Publish to maven central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
        run: ./mvnw -B deploy -DskipTests -Pdeploy
      - name: Set version for next release
        id: next-release-version
        run: |
          NEXT_VERSION=$(echo ${{ github.ref_name }} | awk -F. -v OFS=. '{$NF += 1 ; print}')-SNAPSHOT
          ./mvnw versions:set -DnewVersion="${NEXT_VERSION}"
          echo "next-version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
      - name: Commit next release version
        run: |
          git add pom.xml
          git commit -m "chore: set version to ${{ steps.next-release-version.outputs.next-version }}"
          git push origin HEAD:main
      - name: Create Release
        uses: ncipollo/release-action@v1.21.0
        with:
          artifacts: 'target/digital-blasphemy-client*.jar'
          generateReleaseNotes: true
          makeLatest: true
